Repository geo-smart/deepicedrainpipe, pull requests merged in 2022-11, with the labels that each got.

#2 :memo: Initialize Jupyter Book
  .github/workflows/deploy-book.yml
  .gitignore
  README.md
  book/_config.yml
  book/_toc.yml
  book/intro.md
  book/logo.svg
  book/markdown.md
  book/references.bib
  environment.yml
Labels: documentation

#6 set up netlify for book previews
  .github/workflows/netlifypreview.yml
Labels: preview

#8 :construction_worker: Install build dependencies for Netlify preview
  .github/workflows/deploy-book.yml
  .github/workflows/netlifypreview.yml
Labels: documentation

#9 :heavy_plus_sign: Add jupytext configuration to render py scripts
  book/_config.yml
  environment.yml
Labels: documentation, preview
